server:
  port: 8888

app:
  api-prefix: /api/v1
  api-strip-prefix: 2

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: identity_service
        uri: http://127.0.0.1:8080
        predicates:
        - Path=${app.api-prefix}/identity/**
        filters:
        - StripPrefix=${app.api-strip-prefix}

      - id: profile_service
        uri: http://127.0.0.1:8081
        predicates:
        - Path=${app.api-prefix}/profile/users/**
        filters:
        - StripPrefix=${app.api-strip-prefix}